sudo: required
services:
  - docker
language: python
python:
  - "3.5"
env:
  - DJANGO=1.10 DB=postgres
before_install:
  - curl -L https://github.com/docker/compose/releases/download/2/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin 
install: true
before_script:
  - pip install -U flake8
script:
  - docker-compose -f dev.yml build
  - flake8
  - docker-compose -f dev.yml run django pytest 
