sudo: required
services:
  - docker
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - DJANGO=1.10 DB=postgres
  - DJANGO=1.11 DB=postgres
matrix:
  - python: "3.6"
    env: DJANGO=1.10 DB=postgres
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/2/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin 
script:
  - flake8
  - docker-compose -f dev.yml build
  - docker-compose -f dev.yml run django pytest 
