sudo: required
services:
  - docker
language: python
python:
  - "3.5"
env:
  - DJANGO=1.10 DB=postgres
before_install:
  - curl -L https://github.com/docker/compose/releases/download/1.12.0/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin 
install: 
  - pip install coverage
  - pip install django_coverage_plugin
  - pip install coveralls
script:
  - docker-compose -f dev.yml build
  - docker-compose -f dev.yml up -d
  - docker-compose -f dev.yml run django coverage run manage.py test 
  - docker exec pseapi_django_1 cat /app/.coverage
  - docker cp pseapi_django_1:/app/.coverage .coverage.docker
  - cat .coverage
  - ls -la
  - sudo chmod 777 .coverage
  - 'sudo chown travis: .coverage'
  - sudo chmod 777 .coverage.docker
  - ls -la
after_success:
  - coverage combine
  - coveralls
notifications:
  email:
    recipients:
      - adilson.torres@outlook.com
    on_sucess: never
    on_failure: change
